### ISSUE TITLE
加载更多图片异步请求返回403

### ISSUE THREAD

**Issue by BrianShen** [EmptyChan/SimpleInstagram#1]

**Comment by HyokaChen** [comment]
确实呢，我试了一下也是，好像是它那边需要验证一个其他的参数。还没看出来哪个参数的问题，后期会继续看看。

**Comment by taojunxin** [comment]
碰到同样的问题，希望您找到解决方案后共享一下 @EmptyChan

**Comment by HyokaChen** [comment]
问题处理好了，分析了一下，header里面缺少了一个GIS参数，应该是最近加上去的，现在可以了，注意pip安装一下一个pyexecjs。
