### ISSUE TITLE
不管怎么调试js,就是跳不到加密的js

### ISSUE THREAD

**Issue by wang-weart** [EmptyChan/SimpleInstagram#2]
不知道js怎么调试，老是跳不到你写的这个函数...
希望您有时间写个js调试的过程 谢谢

**Comment by DeyongZheng** [comment]
> 不知道js怎么调试，老是跳不到你写的这个函数...
> 希望您有时间写个js调试的过程 谢谢
我试了可用

**Comment by DeyongZheng** [comment]
> 不知道js怎么调试，老是跳不到你写的这个函数...
> 希望您有时间写个js调试的过程 谢谢
刚刚试过， 可用

**Comment by zdyh** [comment]
刚刚试过 可用

**Comment by wang-weart** [comment]
已经解决了 谢谢

**Comment by HyokaChen** [comment]
还可以用的啊，我还以为已经崩了。那我关了issue了。
